name: Publish to nuget
on:
  push:
    branches:
      - master # Default release branch
jobs:
  publish:
    name: Build, pack & publish
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.x"
          include-prerelease: true

      # Publish
      - name: Publish com.etsoo.Logs on version change
        uses: alirezanet/publish-nuget@v3.0.4
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: com.etsoo.Logs/com.etsoo.Logs.csproj

          # Flag to toggle git tagging, enabled by default
          TAG_COMMIT: false

          # API key to authenticate with NuGet server
          NUGET_KEY: ${{secrets.ETSOONugetKey}}
